version: "3.8"
services:
frontend:
build: .
ports:
- "3000:80"
depends_on:
- db
db:
image: postgres:13-alpine
environment:
POSTGRES_USER: admin # you don't need to change it or remember it.
POSTGRES_PASSWORD: 1234
POSTGRES_DB: mydb
volumes:
- db_data:/var/lib/postgresql/data/
volumes:
db_data:
