version: "3.8"

services:
  frontend:
    build: .
    image: ru0300usman/myapp3:latest # Replace with your Docker Hub details
    ports:
      - "3000:80"
    depends_on:
      - abc
    volumes:
      - my_new_volume:/app/new_data # Mount the new volume to a path in the frontend container

  abc:
    image: postgres:13-alpine # Or your preferred database image
    environment:
      POSTGRES_USER: usman
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb1
    volumes:
      - my_new_volume

volumes:
  abc: # Definition of the new volume
